[workspace]
members = ["crates/ift6251", "crates/point-cloud-renderer"]
resolver = "2"

[profile.fast]
inherits = "release"
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.small]
inherits = "fast"
opt-level = "z"
strip = "symbols"

[profile.opti]
inherits = "fast"
debug = 1
