[package]
name = "point-cloud-renderer"
version = "0.1.0"
edition = "2024"
description = "A point cloud renderer."
authors = ["etiennecollin <collin.etienne.contact@gmail.com>"]
license = "MIT"

[dependencies]
nannou = "0.19.0"
rayon = "1.10.0"
rand = "0.9.0"
e57 = "0.11.9"
